BMforum/BMforum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('comments.urls')),
    path('', include('reports.urls')),
    path('', include('movie_reports.urls')),
    path('', include('movie_comments.urls')),
    path('', include('TopicDiscuss.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

BMforum/comments/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
    path('like/', views.add_like, name = 'like'),
    path('dislike/', views.add_dislike, name = 'dislike'),
]

BMforum/forum/urls.py
from django.urls import path #导入path函数
from .import views 	#从当前的目录下导入views模块
app_name = 'forum'
urlpatterns = [			#网址和处理函数的关系写在urlpatterns列表里面
    path('index/', views.IndexView.as_view(), name='index'),
    path('book_index/', views.BooksIndexView.as_view(), name='book_index'),	#第一个参数是网址，第二个参数是处理函数#第三个name 为传递的参数，这个参数的值作为处理函数index的别名（我也不太懂）
    #path('movies_index/', views.MoviesIndexView.as_view(), name='movie_index'),
    path('groups_index/', views.GroupsIndexView.as_view(), name='groups_index'),
    path('groups/<int:pk>', views.GroupPostView.as_view(), name='group_detail'),
    path('grouppost/<int:pk>', views.GroupDetailView.as_view(), name='group_detailmore'),
    path('books/<int:pk>/', views.PostDetailView.as_view(), name='book_detail'),
    path('movies_index/', views.MoviesIndexView.as_view(), name='movie_index'),
    path('topic/', views.TopicIndexView.as_view(), name='topic_index'),
    path('books/<int:pk>/', views.PostDetailView.as_view(), name='book_detail'),
    path('movies/<int:pk>/', views.MoviePostDetailView.as_view(), name='movie_detail'),
    path('topics/<int:pk>/', views.TopicPostDetailView.as_view(), name='topic_detail'),
    path('add/<int:group_id>', views.add_post, name='add'),
    #path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    #path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    #path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('search/', views.search, name='search'),
    path('book_search/', views.book_search, name='book_search'),
    path('movie_search/', views.movie_search, name='movie_search'),
    path('group_search/', views.group_search, name='group_search'),
    path('group_post_search/', views.group_post_search, name='group_post_search'),
    path('topic_search/', views.topic_search, name='topic_search'),
    #path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('groups_index/<int:pk>', views.add_group, name='addgroup'),
    path('groups_index/<str:name>', views.add_groupmanager, name='addgroupmanager'),
    path(r'delete/<int:pk>/<int:pkk>',views.deleteGroupPost,name = 'delete_grouppost'),
    path(r'top/<int:pk>/<int:pkk>',views.topenGroupPost,name = 'topen_grouppost'),
    path(r'im/<int:pk>/<int:pkk>',views.imGroupPost,name = 'im_grouppost')
]

BMforum/comments/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.urls import reverse
from django.core.validators import MinLengthValidator
class Comment(models.Model):
    title = models.CharField('标题', max_length=70,default='title')
    name = models.CharField('名字', max_length=50)
    text = models.TextField('内容',validators=[MinLengthValidator(25)])
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('forum.Post', verbose_name='文章', on_delete=models.CASCADE)
    #点赞数量
    like_num = models.IntegerField(default = 0)
    dislike_num = models.IntegerField(default = 0)

    class Meta:
        verbose_name = '书评'
        verbose_name_plural = verbose_name
 
    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

class Like(models.Model):
    """点赞"""
    comment = models.ForeignKey("Comment",  on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add = True,verbose_name='创建时间')
    def __str__(self):
        return "%s likes comment %s" % (self.user, self.comment)

class Dislike(models.Model):
    "反对"
    comment = models.ForeignKey("Comment",  on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add = True,verbose_name='创建时间')
    def __str__(self):
        return "%s likes comment %s" % (self.user, self.comment)

BMforum/comments/forms.py
from django import forms
from .models import Comment
 
 
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title','text']

BMforum/comments/views.py
from forum.models import Post
from .models import Comment, Like, Dislike
from django.shortcuts import render,get_object_or_404,render_to_response,HttpResponse, redirect
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.contrib import messages
from users.models import User
import json
import datetime
import markdown

@require_POST
def comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)
 
    # django 将用户提交的数据封装在 request.POST 中，这是一个类字典对象。
    # 我们利用这些数据构造了 CommentForm 的实例，这样就生成了一个绑定了用户提交数据的表单。
    form = CommentForm(request.POST)
 
    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid():
        # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)
        print(comment)
        
        # 将评论和被评论的文章关联起来。
        comment.post = post
        comment.name = request.user
        comment.text = markdown.markdown(comment.text,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        comment.save()
        post.save()
        # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
        # 然后重定向到 get_absolute_url 方法返回的 URL。
        messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')
        return redirect(post)
 
    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

def add_like(request):
    print("add_like launch")
    if request.is_ajax():
        user = request.user
        contentid = request.POST.getlist('contend_id')
        # contentid = request.POST.get('contend_id')
        Commentt = Comment.objects.get(id = contentid[0])       # 获取
        created_time = datetime.datetime.now()
        comment_id = Like.objects.filter(comment_id = Commentt, user_id = request.user.id)
        print(comment_id)
        if comment_id.exists():
            resp = {'status': '已经点赞'}
            return HttpResponse(json.dumps(resp), content_type = "application/json")
        else:
            Commentt.like_num +=1
            Commentt.save()
            Like.objects.update_or_create(user=user, comment = Commentt, created_time = created_time)
            resp = {'errorcode': 100, 'status': '成功点赞'}
            return HttpResponse(json.dumps(resp), content_type="application/json")

def add_dislike(request):
    print("dislike")
    if request.is_ajax():
        user = request.user
        contentid = request.POST.getlist('contend_id')
        # contentid = request.POST.get('contend_id')
        Commentt = Comment.objects.get(id = contentid[0])
        created_time = datetime.datetime.now()
        comment_id = Dislike.objects.filter(comment_id = Commentt, user_id = request.user.id)
        if comment_id.exists():
            resp = {'status': '已经反对'}
            return HttpResponse(json.dumps(resp), content_type = "application/json")
        else:
            Commentt.dislike_num += 1
            Commentt.save()
            Dislike.objects.update_or_create(user = user, comment = Commentt, created_time = created_time)
            resp = {'errorcode': 100, 'status': '成功反对'}
            return HttpResponse(json.dumps(resp), content_type="application/json")

BMforum/templates/comments/inclusions/__list.html
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
    <li class="comment-item">
      <span class="nickname">{{ comment.name }}</span>
      <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
      <div class="text">
        {{ comment.text|linebreaks }}
      </div>
    </li>
  {% empty %}
    暂无评论
  {% endfor %}
</ul>

BMforum/templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.title.id_for_label }}">{{ form.title.label }}：</label>
      {{ form.title }}
      {{ form.title.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>    <!-- row -->
</form>

BMforum/templates/comments/inclusions/_likelist.html
{% load reports_extras %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">热门书评</h3>
  </div>
  <div class="panel-body">
    <ul class="comment-list list-unstyled">
      {% for comment in comment_list %}
      <article>
        <li class="comment-item">
          <span class="nickname">{{ comment.title }}</span>
          <span class="nickname">{{ comment.name }}</span>
          <time class="submit-date" datetime="{{ comment.created_time }}"> {{ comment.created_time }} </time>
          <div class="text">
            {{ comment.text|safe|linebreaks }}
          </div>
        </li>
      </article>
      {% empty %}
      暂无评论
      {% endfor %}
    </ul>
  </div>
</div>

BMforum/templates/comments/inclusions/_list.html
{% load reports_extras %}
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论 </h3>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
  <article>
    <li class="comment-item">
      <span class="nickname">{{ comment.title }}</span>
      <span class="nickname">{{ comment.name }}</span>
      <time class="submit-date" datetime="{{ comment.created_time }}"> {{ comment.created_time }} </time>
      <div class="text">
        {{ comment.text|safe|linebreaks }}
      </div>
      <div>
        <a class="collect2" href="javascript:" content_id2="{{ comment.id }}">
          <button class="btn btn-info"><i class="fa fa-thumbs-up"></i>{{ article.poll_num }} 点赞
            ({{ comment.like_num }})</button>
        </a>
        <a class="collect3" href="javascript:" content_id3="{{ comment.id }}">
          <button class="btn btn-info"><i class="fa fa-thumbs-down"></i>{{ article.poll_num }} 反对
            ({{ comment.dislike_num }})</button>
        </a>
        {% show_report_form comment %}
      </div>
    </li>
  </article>
  {% empty %}
  暂无评论
  {% endfor %}
</ul>

BMforum/templates/comments/inclusions/_list2.html
{% load reports_extras %}
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论 </h3>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
  <article>
    <li class="comment-item">
      <span class="nickname">{{ comment.title }}</span>
      <span class="nickname">{{ comment.name }}</span>
      <time class="submit-date" datetime="{{ comment.created_time }}"> {{ comment.created_time }} </time>
      <div class="text">
        {{ comment.text|safe|linebreaks }}
      </div>
    </li>
  </article>
  {% empty %}
  暂无评论
  {% endfor %}
</ul>