BMforum/BMforum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('comments.urls')),
    path('', include('reports.urls')),
    path('', include('movie_reports.urls')),
    path('', include('movie_comments.urls')),
    path('', include('TopicDiscuss.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

BMforum/forum/urls.py
from django.urls import path #导入path函数
from .import views 	#从当前的目录下导入views模块
app_name = 'forum'
urlpatterns = [			#网址和处理函数的关系写在urlpatterns列表里面
    path('index/', views.IndexView.as_view(), name='index'),
    path('book_index/', views.BooksIndexView.as_view(), name='book_index'),	#第一个参数是网址，第二个参数是处理函数#第三个name 为传递的参数，这个参数的值作为处理函数index的别名（我也不太懂）
    #path('movies_index/', views.MoviesIndexView.as_view(), name='movie_index'),
    path('groups_index/', views.GroupsIndexView.as_view(), name='groups_index'),
    path('groups/<int:pk>', views.GroupPostView.as_view(), name='group_detail'),
    path('grouppost/<int:pk>', views.GroupDetailView.as_view(), name='group_detailmore'),
    path('books/<int:pk>/', views.PostDetailView.as_view(), name='book_detail'),
    path('movies_index/', views.MoviesIndexView.as_view(), name='movie_index'),
    path('topic/', views.TopicIndexView.as_view(), name='topic_index'),
    path('books/<int:pk>/', views.PostDetailView.as_view(), name='book_detail'),
    path('movies/<int:pk>/', views.MoviePostDetailView.as_view(), name='movie_detail'),
    path('topics/<int:pk>/', views.TopicPostDetailView.as_view(), name='topic_detail'),
    path('add/<int:group_id>', views.add_post, name='add'),
    #path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    #path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    #path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('search/', views.search, name='search'),
    path('book_search/', views.book_search, name='book_search'),
    path('movie_search/', views.movie_search, name='movie_search'),
    path('group_search/', views.group_search, name='group_search'),
    path('group_post_search/', views.group_post_search, name='group_post_search'),
    path('topic_search/', views.topic_search, name='topic_search'),
    #path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('groups_index/<int:pk>', views.add_group, name='addgroup'),
    path('groups_index/<str:name>', views.add_groupmanager, name='addgroupmanager'),
    path(r'delete/<int:pk>/<int:pkk>',views.deleteGroupPost,name = 'delete_grouppost'),
    path(r'top/<int:pk>/<int:pkk>',views.topenGroupPost,name = 'topen_grouppost'),
    path(r'im/<int:pk>/<int:pkk>',views.imGroupPost,name = 'im_grouppost')
]

BMforum/comments/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.urls import reverse
from django.core.validators import MinLengthValidator
class Comment(models.Model):
    title = models.CharField('标题', max_length=70,default='title')
    name = models.CharField('名字', max_length=50)
    text = models.TextField('内容',validators=[MinLengthValidator(25)])
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('forum.Post', verbose_name='文章', on_delete=models.CASCADE)
    #点赞数量
    like_num = models.IntegerField(default = 0)
    dislike_num = models.IntegerField(default = 0)

    class Meta:
        verbose_name = '书评'
        verbose_name_plural = verbose_name
 
    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

class Like(models.Model):
    """点赞"""
    comment = models.ForeignKey("Comment",  on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add = True,verbose_name='创建时间')
    def __str__(self):
        return "%s likes comment %s" % (self.user, self.comment)

class Dislike(models.Model):
    "反对"
    comment = models.ForeignKey("Comment",  on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add = True,verbose_name='创建时间')
    def __str__(self):
        return "%s likes comment %s" % (self.user, self.comment)

BMforum/forum/forms.py
from django import forms
from .models import GroupPost

class GroupPostForm(forms.ModelForm):
    class Meta:
        model = GroupPost
        fields = [ 'title', 'body']

BMforum/forum/views.py
import re
import markdown
from django.shortcuts import render, get_object_or_404, redirect
from .models import GroupPost
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.views.generic import ListView, DetailView
from .models import Post, Category, Tag,Group,MemberShip,GroupPost, MoviePost, TopicPost
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone
from users.models import User
from guardian.shortcuts import assign
from guardian.shortcuts import assign_perm
from guardian.shortcuts import get_users_with_perms
from guardian.shortcuts import get_objects_for_user
from django.db.models import Q
from .forms import GroupPostForm
from django.contrib.auth.decorators import login_required


def add_post(request,group_id):
    if request.user.is_authenticated:# 发帖
        #post_list = Post.objects.all().order_by('-created_time')
        group = get_object_or_404(Group, pk = group_id)
        print("先给我把组找出来！")
        print("小组名称为")
        print(group.name)
        print("小组id为")
        print(group_id)
        form = GroupPostForm(request.POST)
        # 判断request的请求方法，如果是post方法，那么就处理数据
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
            post = form.save(commit = False)
            # 将评论和被评论的文章关联起来。
            post.group = group
            post.author = request.user
            print("提交的用户是：")
            print(request.user)
            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            group.save()
            post.save()
            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            messages.add_message(request, messages.SUCCESS, '小组帖子发表成功！', extra_tags='success')
            return redirect(group)
     
        # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
        # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
        context = {
            'post': group,
            'form': form,
        }
        messages.add_message(request, messages.ERROR, '评论发表失败！请增加你发表帖子的字数。', extra_tags='danger')
        return redirect(group)
    else:
        messages.add_message(request,messages.ERROR,"还未登录,请先登录")
        return render(request,'registration/login.html',{'错误':'还未登录！'})
        

class IndexView(ListView):
    model = Post
    template_name = 'forum/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

def login(request):
    if request.method=='POST':
        user = authenticate(request,username=request.POST['用户名'],password=request.POST['密码'])
        if user is None:
            return render(request, 'forum/login.html',{'错误':'用户名不存在！'})
        else:
            login(request,user)
            return rerdirect('forum:index')
    else:
        return render(request,'forum/login.html')

def register(request):
    if request.method=='POST':
        rf = UserCreationForm(request.POST)
        if rf.is_valid():
            user = authenticate(username=rf.cleaned_data['username'],password=rf.cleaned_data['password'])
            login(request, user)
            return rerdirect('forum:index')
    else:
        rf=UserCreationForm()
    content = {'注册表单': rf}
    return render(request,'forum/register.html',content)

def index(request):
    return render(request,'forum/index.html')

def search_index(request):
    return render(request,'forum/search_index.html')

class BooksIndexView(ListView):
    model = Post
    template_name = 'forum/books_index.html'    
    context_object_name = 'books_list'
    paginate_by = 10

# 记得在顶部导入 DetailView
class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'forum/book_detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''
        return post
        
        #添加为小组成员
def add_group(request, pk):
    if request.method == 'GET':
        if request.user.is_authenticated:
            
            group_now  = Group.objects.filter(pk = pk).first()
            user_now = User.objects.filter(username=request.user.username).first()
            mm = MemberShip.objects.filter(person=user_now,group=group_now)
            if not mm:
                m1=MemberShip.objects.create(person=user_now,group=group_now,date_join=timezone.now())
            messages.add_message(request,messages.SUCCESS,"加入小组成功")
            return redirect('forum:groups_index')

        else:
            messages.add_message(request,messages.ERROR,"还未登录,请先登录")
            return render(request,'registration/login.html',{'错误':'还未登录！'})
    else:
        return render(request,'forum/login.html')
##管理员添加
def add_groupmanager(request,name):
    if request.method == 'GET':
        if request.user.is_authenticated:
            
            group_now  = Group.objects.filter(name = name).first()
            user_now = User.objects.filter(username=request.user.username).first()
            gg = GroupPost.objects.filter(group=group_now)
            if  group_now:
                for gp in gg:
                    assign_perm('grouppost_delete',user_now, gp)
            
            messages.add_message(request,messages.SUCCESS,"申请管理员成功")
            return redirect('forum:groups_index')

        else:
            messages.add_message(request,messages.ERROR,"还未登录,请先登录")
            return render(request,'registration/login.html',{'错误':'还未登录！'})
    else:
        return render(request,'forum/login.html')
#删除小组内的帖子
def deleteGroupPost(request,pk,pkk):
    groupp = GroupPost.objects.get(pk=pk)
    groupp.delete()
    messages.add_message(request,messages.SUCCESS,"删除帖子成功")
    return redirect('/groups/'+str(pkk))
#置顶帖子
def topenGroupPost(request,pk,pkk):
    groupp = GroupPost.objects.get(pk=pk)
    groupp.top = True
    groupp.top_time = timezone.now()
    groupp.save()
    messages.add_message(request,messages.SUCCESS,"帖子置顶成功")
    return redirect('/groups/'+str(pkk))
def imGroupPost(request,pk,pkk):
    groupp = GroupPost.objects.get(pk=pk)
    groupp.im = True
    groupp.save()
    messages.add_message(request,messages.SUCCESS,"帖子设精华成功")
    return redirect('/groups/'+str(pkk))
class GroupsIndexView(ListView):
    model = Group        ## 告诉 django 我们要取的数据库模型是class GroupPost,
    template_name = 'forum/groups_index.html'
    context_object_name = 'groups_list'
#paginate_by = 10

class GroupPostView(ListView):
    model = GroupPost
    template_name = 'forum/group_detail.html'
    context_object_name = 'group_post'
    def get_queryset(self):
        c = Group.objects.filter(pk=self.kwargs['pk']).first()
        
        return GroupPost.objects.filter(group=c).order_by('-top_time','created_time')
        
            
    def get_object(self, queryset=None):
        post = super().get_object(queryset=None)
#        md = markdown.Markdown(extensions=[
#            'markdown.extensions.extra',
#            'markdown.extensions.codehilite',
#            TocExtension(slugify=slugify),
#        ])
#        post.members = md.convert(post.members)
#        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
#        post.toc = m.group(1) if m is not None else ''
        return post
        
class GroupDetailView(DetailView):
# 这些属性的含义和 ListView 是一样的
    model = GroupPost
    template_name = 'forum/group_detailmore.html'
    context_object_name = 'grouppost'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(GroupDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''
        return post

class MoviesIndexView(ListView):
    model = MoviePost        ## 告诉 django 我们要取的数据库模型是class Post, 
    template_name = 'forum/movies_index.html'
    context_object_name = 'movies_list'
    #paginate_by = 10
class MoviePostDetailView(DetailView):
    model = MoviePost 
    template_name = 'forum/movie_detail.html'
    context_object_name = 'movie_post'
    def get(self, request, *args, **kwargs):

BMforum/templates/forum/book_detail.html
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
{% extends 'base.html' %}
{% load comments_extras %}
{% load reports_extras %}
{% load ratings %}
{% block main %}
<article class="post post-{{ post.pk}}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name}}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                        datetime="{{ post.created_time}}">{{ post.created_time}}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}

        {% if request.user.is_authenticated %}
        <h3>发表评论</h3>
        {% show_comment_form post %}
        <div class="comment-list-panel">
            {% show_comments post %}
        </div>
        {% else %}
        <div class="comment-list-panel">
            {% show_comments_not_login post %}
        </div>
        {% endif %}
    </div>

</article>

{% endblock main %}

{% block toc %}
<div class="panel panel-default">
    <div class="panel-heading" style=text-align:center>{% ratings object %}</div>
</div>
{% if post.toc %}
<div class="widget widget-content">
    <h3 class="widget-title">目录</h3>
    <div class="toc">
        <ul>
            {{ post.toc|safe }}
        </ul>
    </div>
</div>
{% endif %}
{% endblock toc %}

BMforum/templates/forum/books_index.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% block main %}
{% for book in books_list %}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{{ book.get_absolute_url }}">{{ book.category.name}}</a></span>
            <span class="post-date"><a href="{{ book.get_absolute_url }}"><time class="entry-date"
                        datetime="{{ book.created_time}}">{{ book.created_time}}</time></a></span>
            <span class="post-author"><a href="{{ book.get_absolute_url }}">{{ book.author }}</a></span>
            <span class="comments-link"><a href="{{ book.get_absolute_url }}#comment-area">{{ book.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="{{ book.get_absolute_url }}">{{ book.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ book.excerpt }}...</p>
        <div class="read-more cl-effect-14">
            <a href="{{ book.get_absolute_url }}" class="more-link">继续查看图书内容<span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">暂时没有书籍！</div>
{% endfor %}


{% endblock main %}


{% block search %}
<div id="header-search-box">
    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
    <div id="search-form" class="search-form">
        <form role="search" method="get" id="searchform" action="{% url 'forum:book_search' %}">
            <input type="search" name="q" placeholder="搜索书籍" required>
            <button type="submit"><span class="ion-ios-search-strong"></span></button>
        </form>
    </div>
</div>
{% endblock search %}

BMforum/templates/forum/groups_index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% for group in groups_list %}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href=" {{ group.get_absolute_url }} ">{{ group.name }}</a>
        </h1>
        <div class="entry-meta">
            <h5>小组成员：
                {% for mem in group.members.all%}
                {{mem}}
                {% endfor %}
            </h5>
            <span class="group-created_time"><a href="#">创建时间：{{ group.created_time }} </a></span>
        </div>
    </header>
    <div class="entry-content clearfix">

        <div class="read-more cl-effect-14">
            <a href="{{ group.get_absolute_url }}" class="more-link">查看小组<span class="meta-nav">→</span></a>
            <a href="{{ group.pk }}" class="more-link" method="post" style="margin-right: 25px">加入小组</a>
            <a href="{{ group.name }}" class="more-link" method="post" style="margin-right: 55px">申请管理员</a>

        </div>
    </div>
</article>
{% empty %}
<div class="no-post">暂时还没有小组！</div>
{% endfor %}

{% endblock main %}

{% block search %}
<div id="header-search-box">
    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
    <div id="search-form" class="search-form">
        <form role="search" method="get" id="searchform" action="{% url 'forum:group_search' %}">
            <input type="search" name="q" placeholder="搜索小组" required>
            <button type="submit"><span class="ion-ios-search-strong"></span></button>
        </form>
    </div>
</div>
{% endblock search %}

BMforum/templates/forum/movies_index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% for post in movies_list %}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{{ post.get_absolute_url }}">{{ post.category.name}}</a></span>
            <span class="post-date"><a href="{{ post.get_absolute_url }}"><time class="entry-date"
                        datetime="{{ post.created_time}}">{{ post.created_time}}</time></a></span>
            <span class="post-author"><a href="{{ post.get_absolute_url }}">{{ post.author }}</a></span>
            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}...</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link">继续查看影视内容<span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">暂时没有影视！</div>
{% endfor %}

{% endblock main %}


{% block search %}
<div id="header-search-box">
    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
    <div id="search-form" class="search-form">
        <form role="search" method="get" id="searchform" action="{% url 'forum:movie_search' %}">
            <input type="search" name="q" placeholder="搜索影视" required>
            <button type="submit"><span class="ion-ios-search-strong"></span></button>
        </form>
    </div>
</div>
{% endblock search %}

BMforum/templates/forum/preview.html
{% extends 'base.html' %}
{% load comments_extras %}
 
{% block main %}
  {% show_comment_form post form %}
{% endblock main %}

BMforum/templates/forum/search_index.html
{% extends 'base.html' %}
{% load static %}
{% load forum_extras %}
{% block main %}
<div style="background:rgb(212, 212, 212)">
    <br>
    <h1>&nbsp;&nbsp;&nbsp;&nbsp;搜索到的书籍相关内容</h1>
    <br>

    {% for post in book_post_list %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{{ post.get_absolute_url }}">{{ post.category.name}}</a></span>
                <span class="post-date"><a href="{{ post.get_absolute_url }}"><time class="entry-date"
                            datetime="{{ post.created_time}}">{{ post.created_time}}</time></a></span>
                <span class="post-author"><a href="{{ post.get_absolute_url }}">{{ post.author }}</a></span>
                <span class="comments-link"><a
                        href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }}
                        评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}...</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">没有相关结果！</div>
    {% endfor %}
</div>
<div style="background:rgb(212, 212, 212)">
    <br>
    <h1>&nbsp;&nbsp;&nbsp;&nbsp;搜索到的影视相关内容</h1>
    <br>
    {% for movie in movie_post_list %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{{ movie.get_absolute_url }}">{{ movie.category.name}}</a></span>
                <span class="post-date"><a href="{{ movie.get_absolute_url }}"><time class="entry-date"
                            datetime="{{ movie.created_time}}">{{ movie.created_time}}</time></a></span>
                <span class="post-author"><a href="{{ movie.get_absolute_url }}">{{ movie.author }}</a></span>
                <span class="comments-link"><a href="{{ movie.get_absolute_url }}">{{ movie.comment_set.count }}
                        评论</a></span>
                <span class="views-count"><a href="{{ movie.get_absolute_url }}">{{ movie.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ movie.excerpt }}...</p>
            <div class="read-more cl-effect-14">
                <a href="{{ movie.get_absolute_url }}" class="more-link">继续查看影视内容<span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">没有相关结果！</div>
    {% endfor %}
</div>
<div style="background:rgb(212, 212, 212)">
    <br>
    <h1>&nbsp;&nbsp;&nbsp;&nbsp;搜索到的相关小组</h1>
    <br>
    {% for group in groups_list %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ group.get_absolute_url }}">{{ group.name }}</a>
            </h1>
            <div class="entry-meta">
                <h5>小组成员:
                    {% for mem in group.members.all%}
                    {{mem}}
                    {%endfor%}</h5>
                <span class="group-created_time"><a href="{{ group.get_absolute_url }}">创建时间:{{ group.created_time }}
                    </a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <div class="read-more cl-effect-14">
                <a href="{{ group.get_absolute_url }}" class="more-link">查看小组<span class="meta-nav">→</span></a>
                <a href="{{group.pk}}" class="more-link" method="post" style="margin-right: 25px">加入小组</a>
                <a href="{{group.name}}" class="more-link" method="post" style="margin-right: 55px">申请管理员</a>

            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">没有相关结果！</div>
    {% endfor %}
</div>
<div style="background:rgb(212, 212, 212)">
    <br>
    <h1>&nbsp;&nbsp;&nbsp;&nbsp;搜索到的话题相关内容</h1>
    <br>

    {% for topic in topic_post_list %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class=""><a href="{{ topic.get_absolute_url }}"><time class="entry-date"
                            datetime="{{ topic.created_time}}">创建时间：{{ topic.created_time}}</time></a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ topic.excerpt }}...</p>
            <div class="read-more cl-effect-14">
                <a href="{{ topic.get_absolute_url }}" class="more-link">进入话题<span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">没有相关结果！</div>
    {% endfor %}
    {% endblock main %}
</div>

{% block search %}
<div id="header-search-box">
    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
    <div id="search-form" class="search-form">
        <form role="search" method="get" id="searchform" action="{% url 'forum:search' %}">
            <input type="search" name="q" placeholder="搜索" required>
            <button type="submit"><span class="ion-ios-search-strong"></span></button>
        </form>
    </div>
</div>
{% endblock search %}